### ISSUE TITLE
requires imply ActiveSupport < 3.0, but Gemfile.lock uses latest

### ISSUE THREAD

**Issue by davetron5000** [joshwand/campfire-bot#4]
Pretty much none of the active support stuff works if you have 3.0.x installed, since that code was heavily changed in Rails 3.  The {{Gemfile}} doesn't specify a version and the {{Gemfile.lock}} generated on 12/20 references 3.0.3, which clearly doesn't work at all with this code.

Is the preference to use the v2.x versions or the latest?  If latest, I think we just change

```
require 'active_support'
```

to

```
require 'active_support/all'
```

**Comment by joshwand** [comment]
I have a version using bundler that fixes all this that I'll be pushing shortly. Thanks for the reminder!
